### ISSUE TITLE
All dialects are None

### ISSUE THREAD

**Issue by miroli** [jplusplus/statscraper#3]
Running the example scraper in the readme (Cranes) gives me the following error. It seems that the `dialects` attribute of an `allowed_value` is always None.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/robinlinderborg/dev/statscraper/statscraper/base_scraper.py", line 636, in data
    return self.fetch(query=self.query)
  File "/Users/robinlinderborg/dev/statscraper/statscraper/base_scraper.py", line 629, in fetch
    rs.append(result)
  File "/Users/robinlinderborg/dev/statscraper/statscraper/base_scraper.py", line 263, in append
    if str(v) in av.dialects[d.dialect]:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by rotsee** [comment]
Hur ser koden ut du körde?

**Comment by miroli** [comment]
@rotsee Copy paste från readme'n.

**Comment by rotsee** [comment]
Fixed here for Python2:
https://github.com/jplusplus/statscraper/commit/a32abaf013964f92fb34f497ea26e140fbe30059

and again here for Python3:
https://github.com/jplusplus/statscraper/commit/239b40cfdf634909a07a6ccec4c65abad7b6ed2f

(The last one is a dirty hack that should probably be moved closer to the problematic code, to avoid future bugs in other places)
